/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-01-05 15:39:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<!--[if lt IE 7]> <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\n");
      out.write("<!--[if IE 7]>    <html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\n");
      out.write("<!--[if IE 8]>    <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\n");
      out.write("<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\"> <!--<![endif]-->\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("  <title></title>\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href=\"http://browsehappy.com/\">Upgrade to a different browser</a> or <a href=\"http://www.google.com/chromeframe/?redirect=true\">install Google Chrome Frame</a> to experience this site.</p><![endif]-->\n");
      out.write("  <header>\n");
      out.write("\t  <h1>Wyszukiwarka mieszkań</h1>\n");
      out.write("  </header>\n");
      out.write("  <div class=\"navigationBar\">\n");
      out.write("  \t  <h2 class=\"whereAmI\">\n");
      out.write("  \t\t  <b>1. Personalizacja &raquo;</b>\n");
      out.write("  \t  </h2>\n");
      out.write("  </div>\n");
      out.write("  <form method=\"post\" action=\"fuzzyLogic\">\n");
      out.write("\t\t  <div id=\"main\">\n");
      out.write("\t\t\t  <fieldset>\n");
      out.write("\t\t\t  \t<legend>Jaki masz budżet na zakup nieruchomości ?</legend>\t\t\n");
      out.write("\t\t\t  \t\t\tOd <input name=\"minBudget\" id=\"maxBudget\" type=\"number\"> zł do <input name=\"maxBudget\" id=\"maxBudget\" type=\"number\"> zł \n");
      out.write("\n");
      out.write("\t\t\t  </fieldset>\n");
      out.write("\t\t   </div>\n");
      out.write("\t\t\t<div id=\"main\">\n");
      out.write("\t\t\t  <fieldset>\n");
      out.write("\t\t\t  \t<legend>Jaka powierzchnia Cię interesuje ?</legend>\n");
      out.write("\t\t\t  \t<select name=\"flatSize\">\n");
      out.write("\t\t\t  \t\t<option value=\"verySmallArea\">Bardzo Mała</option>\n");
      out.write("\t\t\t  \t\t<option value=\"smallArea\">Mała</option>\n");
      out.write("\t\t\t  \t\t<option value=\"mediumArea\">Średnia</option>\n");
      out.write("\t\t\t  \t\t<option value=\"largeArea\">Duża</option>\n");
      out.write("\t\t\t  \t\t<option value=\"veryLargeArea\">Bardzo duża</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t  </fieldset>\n");
      out.write("\t\t   </div>\n");
      out.write("\t\t   <div id=\"main\">\n");
      out.write("\t\t     <fieldset>\n");
      out.write("\t\t     \t<legend>Cechy Twojego wymarzonego mieszkania </legend>\n");
      out.write("\t\t     \t\t<ul>\n");
      out.write("\t\t     \t\t\t<li>\n");
      out.write("\t\t     \t\t\t\t<input type=\"checkbox\" name=\"garage\" value=\"garage\" id=\"garage\">\n");
      out.write("\t\t     \t\t\t\t<label for=\"garage\">Garaż</label>\n");
      out.write("\t\t     \t\t\t</li>\n");
      out.write("\t\t     \t\t\t<li>\n");
      out.write("\t\t\t\t     \t\t<input type=\"checkbox\" name=\"closeToCenter\" value=\"closeToCenter\" id=\"closeToCenter\">\n");
      out.write("\t\t\t\t     \t\t<label for=\"closeToCenter\">Odległość od <b>centrum</b> \n");
      out.write("\t\t\t\t     \t\t\t<select name=\"req_distanceFromCenter\">\n");
      out.write("\t\t\t\t     \t\t\t\t<option value=\"2\">Blisko</option>\n");
      out.write("\t\t\t\t     \t\t\t\t<option value=\"5\">Umiarkowana</option>\n");
      out.write("\t\t\t\t     \t\t\t\t<option value=\"15\">Daleko</option>\n");
      out.write("\t\t\t\t     \t\t\t</select>\n");
      out.write("\t\t\t\t     \t\t</label>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t     \t\t<input type=\"checkbox\" name=\"closeToSchool\" value=\"closeToSchool\" id=\"closeToSchool\">\n");
      out.write("\t\t\t\t     \t\t<label for=\"closeToSchool\">Odległość od <b>szkoły</b>\n");
      out.write("\t\t\t\t     \t\t<select name=\"req_distanceFromSchool\">\n");
      out.write("\t\t\t\t     \t\t\t<option value=\"2\">Blisko</option>\n");
      out.write("\t\t\t\t     \t\t\t<option value=\"5\">Umiarkowana</option>\n");
      out.write("\t\t\t\t     \t\t\t<option value=\"15\">Daleko</option>\n");
      out.write("\t\t\t\t     \t\t</select>\n");
      out.write("\t\t\t\t     \t\t\n");
      out.write("\t\t\t\t     \t\t</label>\n");
      out.write("\t\t\t\t     \t</li>\n");
      out.write("\t\t\t\t     \t<li>\n");
      out.write("\t\t\t\t     \t\t<input type=\"checkbox\" name=\"secutityEstate\" value=\"secutityEstate\" id=\"secutityEstate\">\n");
      out.write("\t\t\t\t     \t\t<label for=\"secutityEstate\">Strzeżone osiedle</label>\n");
      out.write("\t\t\t\t     \t</li>\n");
      out.write("\t\t\t\t     \t<li>\n");
      out.write("\t\t     \t\t\t\t<input type=\"checkbox\" name=\"playground\" value=\"playground\" id=\"playground\">\n");
      out.write("\t\t     \t\t\t\t<label for=\"playground\">Plac zabaw na osiedlu</label>\n");
      out.write("\t\t     \t\t\t</li>\n");
      out.write("\t\t     \t\t\t<li>\n");
      out.write("\t\t\t\t     \t\t<input type=\"checkbox\" name=\"elevator\" value=\"elevator\" id=\"elevator\">\n");
      out.write("\t\t\t\t     \t\t<label for=\"elevator\">Winda</label>\n");
      out.write("\t\t\t\t     \t</li>\n");
      out.write("\t\t\t\t     </ul>\n");
      out.write("\t\t     </fieldset>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t    <div id=\"sliderNavigation\">\n");
      out.write("\t\t    \t <input type=\"submit\" value=\"Wyszukaj\" />\n");
      out.write("\t\t    </div>\n");
      out.write("  </form>\n");
      out.write("  <footer>\n");
      out.write("\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\n");
      out.write("  <script>window.jQuery || document.write('<script src=\"js/libs/jquery.min.js\"><\\/script>')</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
